In [ ]:
import numpy as np

a = np.array([10,20,30,40])
print (a)

b = np.arange( 1,11 )
print (b)

c = np.linspace (1,10,5)
print (c)


d = np.random.randint(1,20, size = (3,3))
print ("Matrix A :\n",d, "\n")

e =  np.random.randint(1,20 , size = (3,3))
print ("Matrix B :\n" ,e, "\n\n")

print ( "Sum :\n", d + e , "\n")
print ("Difference :\n ", d - e , "\n")
print ("Product : \n", d * e, "\n")

# Used to multiply elements with each other
print ("Element Multiplication :\n" ,d @ e, "\n")


f = np.array([10,30,50,25,22,68])
print (np.mean(f))
print ("\n", np.max(f), "\n")
print ("\n" , np.min(f), "\n")
print ("\n" , np.std(f), "\n")

print ("Weather Data of Udupi of July")

weather_data = np.array([
    [1, 25],  [2, 25],  [3, 26],  [4, 26],  [5, 27],
    [6, 27],  [7, 26],  [8, 26],  [9, 26],  [10, 26],
    [11, 27], [12, 27], [13, 28], [14, 28], [15, 28],
    [16, 26], [17, 25], [18, 26], [19, 25], [20, 25],
    [21, 26], [22, 25], [23, 25], [24, 35], [25, 25],
    [26, 26], [27, 25], [28, 26], [29, 35], [30, 26],
    [31, 24]
], dtype=float)

temp = weather_data[:,1]
print (" Hottest Day is  " ,np.max(temp) , "\n" )
print (" Coldest Day is  " ,np.min(temp) , "\n" )
print (" Average Temp is  " ,np.average(temp) , "\n" )

days = weather_data[:,0]
date_35 = days[temp>=35]
print ("\n Days with temp greater than 35 : ", date_35)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]
Matrix A :
 [[ 5  1 15]
 [16 18  6]
 [ 6 13 10]]

Matrix B :
 [[16  6 17]
 [ 6  6 18]
 [ 2 10 10]]


Sum :
 [[21  7 32]
 [22 24 24]
 [ 8 23 20]]

Difference :
  [[-11  -5  -2]
 [ 10  12 -12]
 [  4   3   0]]

Product :
 [[ 80   6 255]
 [ 96 108 108]
 [ 12 130 100]]

Element Multiplication :
 [[116 186 253]
 [376 264 656]
 [194 214 436]]

34.166666666666664

 68


 10


 19.273614664152184

Weather Data of Udupi of July
 Hottest Day is   35.0

 Coldest Day is   24.0

 Average Temp is   26.548387096774192


 Days with temp greater than 35 :  [24. 29.]

In [ ]:
from sklearn import datasets

iris = datasets.load_iris(as_frame = True)

# iris = load_iris (as_frame = True)
df = iris.frame

df.head()

#activity 4 : selecting data

df [['sepal length (cm)', 'target']]

df.iloc[:5]

df.loc [10 : 20]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
10,5.4,3.7,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
13,4.3,3.0,1.1,0.1,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0
20,5.4,3.4,1.7,0.2,0

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AML_MSIS/titanic.csv")
df.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [ ]:
df ['Age'] = df ['Age'].fillna(0)
surv = df[df ['Survived'] == 1 ]
non_surv = df[df ['Survived'] == 0 ]


#total number of passengers
print ("\n Total Passengers : " ,len(df))


#average age of survivors and non survivors
print ("\n Average age of Survivors : " ,surv['Age'].mean())
print ("\n Average age of Non Survivors : " ,non_surv['Age'].mean())

#passengers older than 60
print ("\n Passengers older than 60 : ", len(df[df['Age'] > 60]))


#average fare for each passenger pclass
c1 = df[df['Pclass'] == 1]
c2 = df[df['Pclass'] == 2]
c3 = df[df['Pclass'] == 3]
print ("\n Average fare for each passenger pclass 1 : ", c1['Fare'].mean() )
print ("\n Average fare for each passenger pclass 2 : ", c2['Fare'].mean() )
print ("\n Average fare for each passenger pclass 3 : ", c3['Fare'].mean() )

 Total Passengers :  887

 Average age of Survivors :  28.408391812865496

 Average age of Non Survivors :  30.13853211009174

 Passengers older than 60 :  26

 Average fare for each passenger pclass 1 :  84.1546875

 Average fare for each passenger pclass 2 :  20.662183152173913

 Average fare for each passenger pclass 3 :  13.707707392197124

In [12]:
!git push -u origin main

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 468 bytes | 78.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/dhanusherramuri/AML_MSIS.git
   83a94e0..8c2c3c8  main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.